## NumPy

In [1]:
import numpy as np

### np.array()

In [2]:
l = [1, 2, 3, 4, 5]

In [8]:
npa = np.array(l)

In [9]:
type(l), type(npa)

(list, numpy.ndarray)

In [10]:
npa.shape

(5,)

In [14]:
l.append('string')

In [15]:
npa = np.array(l)

In [16]:
npa

array(['1', '2', '3', '4', '5', '6', 'string'], dtype='<U21')

In [17]:
l1 = [1, 4, 9, 16]

In [18]:
l+l1

[1, 2, 3, 4, 5, 6, 'string', 1, 4, 9, 16]

In [19]:
np.array(l+l1)

array(['1', '2', '3', '4', '5', '6', 'string', '1', '4', '9', '16'],
      dtype='<U21')

In [20]:
l + [20]

[1, 2, 3, 4, 5, 6, 'string', 20]

In [21]:
l = [[1,2], [3,4], [3,4]]

In [23]:
npa2d = np.array(l)

In [24]:
npa2d

array([[1, 2],
       [3, 4],
       [3, 4]])

In [25]:
npa2d.shape

(3, 2)

In [26]:
npa2d = np.array(l, dtype = 'float')

In [27]:
npa2d

array([[1., 2.],
       [3., 4.],
       [3., 4.]])

In [28]:
npa2d.astype('int')

array([[1, 2],
       [3, 4],
       [3, 4]])

In [31]:
npa2d = npa2d.astype('str')

In [32]:
npa2d[0][0] + str(1)

'1.01'

### np.nan and np.inf

In [33]:
np.nan == np.nan

False

In [35]:
np.inf == np.inf

True

In [36]:
None == None

True

In [39]:
npa2d = npa2d.astype('float') 

In [40]:
npa2d

array([[1., 2.],
       [3., 4.],
       [3., 4.]])

In [41]:
npa2d.astype('int')

array([[1, 2],
       [3, 4],
       [3, 4]])

In [42]:
npa2d[0][0] = np.nan
npa2d[1][1] = np.inf

In [43]:
npa2d

array([[nan,  2.],
       [ 3., inf],
       [ 3.,  4.]])

In [44]:
np.isnan(npa2d)

array([[ True, False],
       [False, False],
       [False, False]])

In [45]:
np.isinf(npa2d)

array([[False, False],
       [False,  True],
       [False, False]])

In [46]:
flag = np.isnan(npa2d) | np.isinf(npa2d)
flag

array([[ True, False],
       [False,  True],
       [False, False]])

In [47]:
npa2d[flag]

array([nan, inf])

In [48]:
npa2d[flag] = 0
npa2d

array([[0., 2.],
       [3., 0.],
       [3., 4.]])

### Statistical Operations 


mean, variance, standard deviation using Numpy:(Its important during feature Extraction)

In [49]:
npa2d

array([[0., 2.],
       [3., 0.],
       [3., 4.]])

In [50]:
npa2d.mean()

2.0

In [51]:
npa2d.min()

0.0

In [52]:
npa2d.max()

4.0

In [53]:
npa2d.std()

1.5275252316519468

In [54]:
npa2d.var()

2.3333333333333335

In [57]:
np.median(npa2d)

2.5

### Shape(), Reshape(), Ravel()

In [58]:
npa2d

array([[0., 2.],
       [3., 0.],
       [3., 4.]])

In [59]:
npa2d.shape

(3, 2)

In [62]:
npa2d.reshape(2, 3)

array([[0., 2., 3.],
       [0., 3., 4.]])

In [64]:
npa2d.reshape(1, 6)

array([[0., 2., 3., 0., 3., 4.]])

### Ravel() helps in converting 2d to 1d 

In [65]:
npa2d.reshape(1, 6).ravel()

array([0., 2., 3., 0., 3., 4.])

We, can also use flatten to do the same

In [66]:
npa2d.reshape(1, 6).flatten()

array([0., 2., 3., 0., 3., 4.])

### Sequence, repetitions and random numbers 

#### arange(), linspace(), random(), zeros(), and ones() 

It is used to arrange the number within a range:>

With this np.arange() we create a array where the difference b/w the two consecutive numbers are equal

In [69]:
np.arange(1, 5, dtype = 'float')

array([1., 2., 3., 4.])

In [73]:
np.arange(1, 20, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

with linspace() we create an array where the difference b/w these consecutive numbers depends on how many values we want in that particular array

In [76]:
np.linspace(1, 20, 3)

array([ 1. , 10.5, 20. ])

Here, while using linspace(), the third argument does not defines the steps, it defines the exact number that is to be shown if there is 3 then there will be 3 numbers:>

In [77]:
np.linspace(1, 20, 5)

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

logspace() is used to generate the array log values are generated 

In [79]:
np.logspace(1, 50, 10)

array([1.00000000e+01, 2.78255940e+06, 7.74263683e+11, 2.15443469e+17,
       5.99484250e+22, 1.66810054e+28, 4.64158883e+33, 1.29154967e+39,
       3.59381366e+44, 1.00000000e+50])

It helps in generating the array, which will contains zeroes inside it.

In [80]:
np.zeros([1, 6])

array([[0., 0., 0., 0., 0., 0.]])

In [81]:
np.zeros([1,2,3])

array([[[0., 0., 0.],
        [0., 0., 0.]]])

In [82]:
np.ones([1, 2])

array([[1., 1.]])

In [83]:
np.ones([1, 10])

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

Tile means we want to repeat the particular sequence, 

In [85]:
np.tile([1,2], 3)

array([1, 2, 1, 2, 1, 2])

In the same way we can do repeat by using repeat()

In [86]:
np.repeat([1,2], 3)

array([1, 1, 1, 2, 2, 2])

The difference between np.tile() and np.repeat() is that tile works by concatenating the whole list together whereas, repeat() first concatenate the first element of the list, then the second element of the list

### np.random()

It is used to generate random number of array


In [91]:
np.random.rand(3, 3)

array([[0.22279434, 0.2267309 , 0.13515835],
       [0.82732842, 0.46846743, 0.65063691],
       [0.13848353, 0.54969032, 0.78034569]])

randint() is used to generate random integer numbers

In [89]:
np.random.randint(0, 10, [3, 3])

array([[9, 8, 9],
       [8, 0, 4],
       [3, 7, 9]])

random.seed() is used to fix the random number 

In [100]:
np.random.seed(1)
np.random.randint(0, 10, [3, 3])

array([[5, 8, 9],
       [5, 0, 0],
       [1, 7, 6]])

### np.unique()

It is used to generate the unique numbers inside the array

In [101]:
np.unique(npa2d)

array([0., 2., 3., 4.])

If, we have to find the frequency of the unique number then we'll use return_counts, which will give the frequency

In [103]:
np.unique(npa2d, return_counts=True)

(array([0., 2., 3., 4.]), array([2, 1, 2, 1]))

### Where()

In [104]:
arr = np.array([2,3,4,5,56,767,78,89,123])

In [105]:
arr

array([  2,   3,   4,   5,  56, 767,  78,  89, 123])

In [106]:
np.where(arr>10)

(array([4, 5, 6, 7, 8]),)

Where is used here to give the condition clause inside the array

In [107]:
index = np.where(arr>10)
arr[index]

array([ 56, 767,  78,  89, 123])

In [108]:
index = np.where(arr<10)
arr[index]

array([2, 3, 4, 5])

In [111]:
index = np.where(arr==56)
arr[index]

array([56])

To find the argument of the maximum number 

In [112]:
arr.argmax()

5

To find the argumnent of the minimum number 

In [113]:
arr.argmin()

0

### File Read and Write

In [114]:
npa2d

array([[0., 2.],
       [3., 0.],
       [3., 4.]])

In [115]:
np.savetxt('npa2d.csv', npa2d, delimiter=',')

In [117]:
np.loadtxt('npa2d.csv', delimiter=',')

array([[0., 2.],
       [3., 0.],
       [3., 4.]])

Save the values in byte format by using np.save()

In [118]:
np.save('data.npy', npa2d)

In [119]:
np.load('data.npy')

array([[0., 2.],
       [3., 0.],
       [3., 4.]])

#### Saving 2 arrays together using np.savez()

In [120]:
np.savez('both.npz', arr, npa2d)

In [121]:
np.load('both.npz')

In [123]:
d = np.load('both.npz')

In [125]:
d[d.files[1]]

array([[0., 2.],
       [3., 0.],
       [3., 4.]])

### Concatenate And Sorting

In [126]:
npa2d

array([[0., 2.],
       [3., 0.],
       [3., 4.]])

In [135]:
#if axis=0 then it is vertical concatenated
np.concatenate([npa2d, npa2d], axis = 0) 

array([[0., 2.],
       [3., 0.],
       [3., 4.],
       [0., 2.],
       [3., 0.],
       [3., 4.]])

In [136]:
#if axis=1 then it is horizontal concatenated
np.concatenate([npa2d, npa2d], axis = 1) 

array([[0., 2., 0., 2.],
       [3., 0., 3., 0.],
       [3., 4., 3., 4.]])

#### Concatenating vertically using np.vstack()

In [137]:
np.vstack([npa2d, npa2d])

array([[0., 2.],
       [3., 0.],
       [3., 4.],
       [0., 2.],
       [3., 0.],
       [3., 4.]])

#### Concatenating horizontally using np.hstack() 

In [139]:
npa = np.hstack([npa2d, npa2d])

### Sorting  

In [140]:
npa

array([[0., 2., 0., 2.],
       [3., 0., 3., 0.],
       [3., 4., 3., 4.]])

In [143]:
# it sorts the array rows by rows
npa.sort()

In [144]:
npa

array([[0., 0., 2., 2.],
       [0., 0., 3., 3.],
       [3., 3., 4., 4.]])

### Working With Dates

In [145]:
d = np.datetime64('2020-12-01 23:34:19')

In [146]:
d

numpy.datetime64('2020-12-01T23:34:19')

In [148]:
d + 10

numpy.datetime64('2020-12-01T23:34:29')

#### Creating one day

In [149]:
one_day = np.timedelta64(1, 'D')

In [150]:
d + one_day

numpy.datetime64('2020-12-02T23:34:19')

#### Add one minute

In [151]:
oneminute = np.timedelta64(1, 'm')


In [152]:
d+oneminute

numpy.datetime64('2020-12-01T23:35:19')

## ---------------------------------------END-------------------------------